name: Quadio Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
      postgres:
        image: postgres
        # env:
        #   POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello from Quadio Node.js
